import "server-only";
export type PokemonProduct={id:string;name:string;url:string;apiUrl:string;imageUrl:string;marketPriceCents:number;nearMintNormalCents:number;lowCents:number;midCents?:number;highCents:number;cardmarket?:{trendPrice:number;avg1:number;avg7:number;avg30:number};totalSold:number|null;dailySold:number|null;history:{label:string;cents:number}[]};
const base="https://api.pokemontcg.io/v2/cards";
const fallback:PokemonProduct[]=[{id:"xy8-48",name:"Pikachu · XY Breakthrough",url:"https://www.tcgplayer.com/product/107167/pokemon-xy-breakthrough-pikachu?page=1&Language=English&Printing=Normal",apiUrl:`${base}/xy8-48`,imageUrl:"https://images.pokemontcg.io/xy8/48.png",marketPriceCents:109,nearMintNormalCents:109,lowCents:75,midCents:105,highCents:199,totalSold:null,dailySold:null,history:[]}];
type Card={id:string;name:string;images?:{small?:string;large?:string};tcgplayer?:{url?:string;prices?:Record<string,{market?:number;mid?:number;low?:number;high?:number}>};cardmarket?:{prices?:{trendPrice?:number;avg1?:number;avg7?:number;avg30?:number}}};
function map(c:Card):PokemonProduct{const entries=Object.entries(c.tcgplayer?.prices||{}), normal=entries.find(([k])=>/normal/i.test(k)&&/market/i.test(k))?.[1]||entries.find(([,v])=>v.market!=null)?.[1]||{}, cents=Math.round((normal.market||0)*100),cm=c.cardmarket?.prices;return{id:c.id,name:c.name,url:c.tcgplayer?.url||`https://www.tcgplayer.com/search/pokemon/product?q=${encodeURIComponent(c.name)}`,apiUrl:`${base}/${c.id}`,imageUrl:c.images?.large||c.images?.small||"/pokeball.svg",marketPriceCents:cents,nearMintNormalCents:cents,lowCents:Math.round((normal.low||normal.market||0)*100),midCents:Math.round((normal.mid||normal.market||0)*100),highCents:Math.round((normal.high||normal.market||0)*100),cardmarket:cm?.trendPrice!=null&&cm.avg1!=null&&cm.avg7!=null&&cm.avg30!=null?{trendPrice:cm.trendPrice,avg1:cm.avg1,avg7:cm.avg7,avg30:cm.avg30}:undefined,totalSold:null,dailySold:null,history:[]}}
async function request(path:string){const r=await fetch(path,{headers:process.env.POKEMON_TCG_API_KEY?{"X-Api-Key":process.env.POKEMON_TCG_API_KEY}:undefined,cache:"no-store",signal:AbortSignal.timeout(10000)});return r.ok?r.json():null}
const searchCache=new Map<string,PokemonProduct[]>(); const productCache=new Map<string,PokemonProduct>();
function scrape(html:string):PokemonProduct[]{const out:PokemonProduct[]=[];for(const m of html.matchAll(/href="([^"]*product\/(\d+)[^"]*)"[\s\S]{0,5000}?(?:productName|name)[^>]*>([^<]{3,120})[\s\S]{0,1500}?(?:market price|marketPrice)[^$]*\$([\d,.]+)/gi)){const [,href,id,n,price]=m;const cents=Math.round(Number(price.replace(/,/g,""))*100);if(!cents||out.some(x=>x.id===id))continue;out.push({id,name:n.trim(),url:href.startsWith("http")?href:`https://www.tcgplayer.com${href}`,apiUrl:`${base}/${id}`,imageUrl:"/pokeball.svg",marketPriceCents:cents,nearMintNormalCents:cents,lowCents:cents,highCents:cents,totalSold:null,dailySold:null,history:[]})}return out}
export async function searchPokemon(query:string,page=1){const q=query.trim();if(!q)return{products:fallback,page:1,totalPages:1,source:"Pokemon TCG API results"};try{let all=searchCache.get(q);if(!all){const seen=new Set<string>();all=[];for(let n=1;n<=1;n++){try{const j=await request(`${base}?q=${encodeURIComponent(`name:${q}`)}&page=${n}&pageSize=20`);for(const card of (j?.data||[]) as Card[])if(!seen.has(card.id)){seen.add(card.id);all.push(map(card))}}catch{}}if(all.length)searchCache.set(q,all)}all.forEach(p=>productCache.set(p.id,p));const products=all.slice((Math.max(1,page)-1)*10,Math.max(1,page)*10);if(products.length)return{products,page,totalPages:Math.min(2,Math.max(1,Math.ceil(all.length/10))),source:"Pokemon TCG API results"}}catch{}return{products:[],page,totalPages:1,source:"No Pokemon TCG API results loaded. Try searching again."}}
export async function getPokemonProduct(id:string){const cached=productCache.get(id);if(cached)return cached;try{const j=await request(`${base}/${encodeURIComponent(id)}`);if(j?.data){const p=map(j.data);productCache.set(id,p);return p}}catch{}return fallback.find(p=>p.id===id)||null}
