import "server-only";
export type PokemonProduct={id:string;name:string;url:string;apiUrl:string;imageUrl:string;marketPriceCents:number;nearMintNormalCents:number;lowCents:number;midCents?:number;highCents:number;cardmarket?:{trendPrice:number;avg1:number;avg7:number;avg30:number};totalSold:number|null;dailySold:number|null;history:{label:string;cents:number}[]};
const base="https://api.pokemontcg.io/v2/cards";
const fallback:PokemonProduct[]=[{id:"xy8-48",name:"Pikachu · XY Breakthrough",url:"https://www.tcgplayer.com/product/107167/pokemon-xy-breakthrough-pikachu?page=1&Language=English&Printing=Normal",apiUrl:`${base}/xy8-48`,imageUrl:"https://images.pokemontcg.io/xy8/48.png",marketPriceCents:109,nearMintNormalCents:109,lowCents:75,midCents:105,highCents:199,totalSold:null,dailySold:null,history:[]}];
type Card={id:string;name:string;images?:{small?:string;large?:string};tcgplayer?:{url?:string;prices?:Record<string,{market?:number;mid?:number;low?:number;high?:number}>};cardmarket?:{prices?:{trendPrice?:number;avg1?:number;avg7?:number;avg30?:number}}};
function map(c:Card):PokemonProduct{const entries=Object.entries(c.tcgplayer?.prices||{}), normal=entries.find(([k])=>/normal/i.test(k)&&/market/i.test(k))?.[1]||entries.find(([,v])=>v.market!=null)?.[1]||{}, cents=Math.round((normal.market||0)*100),cm=c.cardmarket?.prices;return{id:c.id,name:c.name,url:c.tcgplayer?.url||`https://www.tcgplayer.com/search/pokemon/product?q=${encodeURIComponent(c.name)}`,apiUrl:`${base}/${c.id}`,imageUrl:c.images?.large||c.images?.small||"/pokeball.svg",marketPriceCents:cents,nearMintNormalCents:cents,lowCents:Math.round((normal.low||normal.market||0)*100),midCents:Math.round((normal.mid||normal.market||0)*100),highCents:Math.round((normal.high||normal.market||0)*100),cardmarket:cm?.trendPrice!=null&&cm.avg1!=null&&cm.avg7!=null&&cm.avg30!=null?{trendPrice:cm.trendPrice,avg1:cm.avg1,avg7:cm.avg7,avg30:cm.avg30}:undefined,totalSold:null,dailySold:null,history:[]}}
async function request(path:string){for(let attempt=0;attempt<5;attempt++){const r=await fetch(path,{headers:process.env.POKEMON_TCG_API_KEY?{"X-Api-Key":process.env.POKEMON_TCG_API_KEY}:undefined,cache:"no-store",signal:AbortSignal.timeout(10000)});if(r.ok){try{return await r.json()}catch{return null}}if(r.status===429){const retry=Number(r.headers.get("retry-after"));await new Promise(x=>setTimeout(x,Number.isFinite(retry)&&retry>0?retry*1000:1500*(attempt+1)));continue}return null}return null}
const searchCache=new Map<string,PokemonProduct[]>(); const productCache=new Map<string,PokemonProduct>();
function scrape(html:string):PokemonProduct[]{const out:PokemonProduct[]=[];for(const m of html.matchAll(/href="([^"]*product\/(\d+)[^"]*)"[\s\S]{0,5000}?(?:productName|name)[^>]*>([^<]{3,120})[\s\S]{0,1500}?(?:market price|marketPrice)[^$]*\$([\d,.]+)/gi)){const [,href,id,n,price]=m;const cents=Math.round(Number(price.replace(/,/g,""))*100);if(!cents||out.some(x=>x.id===id))continue;out.push({id,name:n.trim(),url:href.startsWith("http")?href:`https://www.tcgplayer.com${href}`,apiUrl:`${base}/${id}`,imageUrl:"/pokeball.svg",marketPriceCents:cents,nearMintNormalCents:cents,lowCents:cents,highCents:cents,totalSold:null,dailySold:null,history:[]})}return out}
export async function searchPokemon(query:string,page=1,refresh?:string){const raw=query.trim();if(!raw)return{products:[],page:1,totalPages:1,source:"Pokemon TCG API results"};const q=raw.replace(/[-_]+/g," ").replace(/\s+/g," ").trim(),apiName=q.split(" ")[0],cacheKey=refresh?`${q}:${refresh}`:q;try{let all=searchCache.get(cacheKey)||[];if(!all.length){const collect=(j:any,into:PokemonProduct[],seen:Set<string>)=>{for(const card of (j?.data||[]) as Card[])if(!seen.has(card.id)){seen.add(card.id);try{into.push(map(card))}catch{}}};const full=await request(`${base}?q=${encodeURIComponent(q)}&page=1&pageSize=50`);const seen=new Set<string>();const fullItems:PokemonProduct[]=[];collect(full,fullItems,seen);const matches=fullItems.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));if(matches.length)all=matches;else{all=fullItems;const named=await request(`${base}?q=${encodeURIComponent(`name:${apiName}`)}&page=1&pageSize=50`);collect(named,all,seen)}}if(all.length)searchCache.set(cacheKey,all);all.forEach(p=>productCache.set(p.id,p));const products=all.slice((Math.max(1,page)-1)*10,Math.max(1,page)*10);if(products.length)return{products,page,totalPages:Math.min(5,Math.max(1,Math.ceil(all.length/10))),source:"Pokemon TCG API results"}}catch{}return{products:[],page,totalPages:1,source:"No Pokemon TCG API results loaded. Try searching again."}}
export async function getPokemonProduct(id:string){const cached=productCache.get(id);if(cached)return cached;try{const j=await request(`${base}/${encodeURIComponent(id)}`);if(j?.data){const p=map(j.data);productCache.set(id,p);return p}}catch{}return fallback.find(p=>p.id===id)||null}
